### ISSUE TITLE
dateTimeLabelFormat is object rather than string

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#17092]
#### Expected behaviour
Chart is rendered

#### Actual behaviour
Javascript error "Uncaught TypeError: d.indexOf is not a function"

#### Live demo with steps to reproduce
https://jsfiddle.net/0dme4na3/

#### Product version
Highcharts

#### Affected browser(s)
10.0.0

#### Suggested fix

It seems like after the dateTimeLabelFormat value is acquired from axis.dateTime.getXDateFormat() function we need to extract the main key if it exists, just like few lines above. The suggested patch which fixes this is:

```
diff --git a/ts/Core/Axis/Tick.ts b/ts/Core/Axis/Tick.ts
index 01e8b7307a..cde6031b85 100644
--- a/ts/Core/Axis/Tick.ts
+++ b/ts/Core/Axis/Tick.ts
@@ -251,6 +251,9 @@ class Tick {
                     value,
                     (options.dateTimeLabelFormats || {}) as any
                 );
+                if (dateTimeLabelFormat.main) {
+                    dateTimeLabelFormat = dateTimeLabelFormat.main;
+                }
             }
         }
```

**Comment by karolkolodziej** [comment]
Thank you for reporting that bug and thank you for that workaround which works well.

Demo: https://jsfiddle.net/BlackLabel/60cx4ynt/

**Comment by dmitrygorbenko** [comment]
Thank you for the workaround !
It works

**Comment by dmitrygorbenko** [comment]
Hi guys,
any updates on this issue ?
I think the fix should be easy to implement, well, I hope )
Just don't want this issue be forgotten.
Thanks

**Comment by karolkolodziej** [comment]
It works correctly in version 10.2.0 -[demo](https://jsfiddle.net/BlackLabel/fpc7gdor/).
This issue was fixed by https://github.com/highcharts/highcharts/commit/a7ab03128b9691b5d32763f61cb68746acbef20c and can be closed as resolved.
