### ISSUE TITLE
Errors appear in console and bars are blinking with horizontal scroll

### ISSUE THREAD

**Issue by lifemaster-softserve** [highcharts/highcharts#13985]
#### Expected behaviour
Scroll shouldn't throw errors in console and bars shouldn't blinking while scrolling.

#### Actual behaviour
1. A lot of errors appear in console:
`Error: <rect> attribute y: Expected length, "NaN".`
`Error: <rect> attribute height: Expected length, "NaN".`

2. Bars are blinking while scrolling

#### Live demo with steps to reproduce
https://plnkr.co/edit/kZ40poSjW0Hm8UMD?open=lib%2Fapp.ts&deferRun=1&preview

1. Open console;
2. Just scroll horizontal scroll;

Bars are blinking and there are a lot of errors in console.

#### Product version
Errors are thrown since version 8.0.0
Bars are blinking since version 7.0.3

Till version 7.0.2 everything is fine.

#### Affected browser(s)
Google Chrome 84.0.4147.105 (x64)
Mozilla Firefox 79.0 (x64)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @lifemaster-softserve 

*Internal note:*
Bisected to commit fde683209c - caused by cropping points that are outside the visible xAxis extremes. In this particular case, that means we may have zoomed range that contains zero points (range = 0.5) which hides yAxis and causes these rendering errors and artifacts.

**Comment by lifemaster-softserve** [comment]
Your workaround works fine but I have problem to do it in Angular with TypeScript:

`Property 'seriesTypes' does not exist on type 'typeof import("highcharts/highcharts")'. Did you mean 'seriesType'?`

So, `(Highcharts as any).seriesTypes.column.prototype.cropShoulder = 1;` works fine. Hope you will fix this soon.

**Comment by lifemaster-softserve** [comment]
@pawelfus I have met one more issue with already applied workaround you suggested. Please, follow this link and try to use horizontal scroll. We can see the same issue again.

https://jsfiddle.net/oe49pa0n/

**Comment by pawelfus** [comment]
Thank you for posting this issue :) 

It's not a perfect solution, but for now, the best would be to use [`series.getExtremesFromAll`](https://api.highcharts.com/highcharts/series.column.getExtremesFromAll) option: https://jsfiddle.net/BlackLabel/qL4gzp2d/ - downside is that yAxis extremes are always calculated according to the entire dataset, not using the visible points only.

**Comment by lifemaster-softserve** [comment]
Thank you, @pawelfus It works for me.

**Comment by pawellysy** [comment]
unstale
