### ISSUE TITLE
[7.1.3] TS error:  Property 'yData' does not exist on type 'Point'.

### ISSUE THREAD

**Issue by ViieeS** [highcharts/highcharts#11700]
When I try to compile my code after update to 7.1.3, I get this error:

```
error TS2339: Property 'yData' does not exist on type 'Point | Series'.
Property 'yData' does not exist on type 'Point'.
```

Code:
```ts
legend: {
   labelFormatter() {
         const yTotal = this.yData.reduce((acc, val) => acc + val, 0);
         return `${this.name} ${formatNumber(yTotal, locale, '1.0-2')}`;
   },
}
```

I guess some problem with [interfaces](https://api.highcharts.com/highcharts/legend.labelFormatter) in 7.1.3, because if I ignore it, it goes away in run-time. Also 7.1.2 works fine.

#### Product version
Highcharts 7.1.3

**Comment by sebastianbochan** [comment]
Hi @ViieeS,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by pawelfus** [comment]
I'm not sure if this is a bug. In `labelFormatter` you can access Point (one legend item for each Point in Pie Series) or Series element (one legend item for each Series, e.g. line series). In this case, using type assertion is the easiest solution IMHO:

`this.yData` -> `(this as Highcharts.Series).yData`

Alternatively check if this element is a Series or a Point:

```js
        function isSeries(
            pointOrSeries: Highcharts.Point | Highcharts.Series
        ): pointOrSeries is Highcharts.Series {
            return (pointOrSeries as Highcharts.Series).yData !== undefined;
        }
```

Then formatter could look like this:
```js
   labelFormatter() {
            if (isSeries(this)) {
                // Series:
                const yTotal = this.yData && this.yData.reduce((acc, val) => acc + val, 0);
                return `${this.name} ${formatNumber(yTotal, locale, '1.0-2')}`;
            } else {
                // Point:
                return this.name || '';
            }
   },
```

**Comment by bre1470** [comment]
@pawelfus It would be enough to actually compare agains the class:
```ts
if (this instanceof Highcharts.Point) {
    return 'point';
} else {
    return 'series';
}
```

**Comment by bre1470** [comment]
It is working as intended.

**Comment by ViieeS** [comment]
@bre1470 Thanks for clarification! However, it's bad practice to change interfaces in minor versions, especially adding breaking changes.

**Comment by ViieeS** [comment]
@bre1470 @pawelfus I tried your solutions, but no luck. I'am still getting error:

`error TS2551: Property 'yData' does not exist on type 'Series'. Did you mean 'data'?`

Also, I couldn't find a definition of `Series.yData` property in `node_modules/highcharts/highcharts.d.ts`.

**Comment by bre1470** [comment]
@ViieeS 
`Series.yData` itself is an internal property and instead `Series.data` should be used. TypeScript declarations cover only the official properties mentioned in our [API documentation](https://api.highcharts.com/). Additionally the TypeScript support is still in beta stage because of the long review process which also implies minimal changes because of type bugs.

If you still insist to access the data, you can instead of an `any` cast add additional declarations like described in our documentation: https://www.highcharts.com/docs/advanced-chart-features/typescript
```ts
declare module 'highcharts' {
    interface Series {
        yData?: Dictionary<(number|null)>;
    }
}
```
There is though no guarantee that this is stable, as internal behaviour on runtime might change at anytime.
