### ISSUE TITLE
Waterfall - not working in 4.2.4

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5218]
#### Expected behaviour
Working

#### Actual behaviour
Not working

#### Live demo of the issue
http://www.highcharts.com/demo/waterfall

#### Steps to reproduce the behaviour
1. See that there is not chart
2. Error in browser console: *"highcharts-more.src.js:1762Uncaught TypeError: correctFloat is not a function"*
(http://jsfiddle.net/3g75oa0v/)

#### Affected browser(s)
All

#### Workaround
Use 4.2.3 - http://jsfiddle.net/3g75oa0v/1/

**Comment by TorsteinHonsi** [comment]
> Expected behaviour, Working

Okay, in the future you don't have to repeat that :) Better if you delete the obvious headlines.

Anyway I suspect that you are loading [highcharts.js v4.2.3 and highcharts-more.js v4.2.4](http://jsfiddle.net/highcharts/3g75oa0v/2/)? Probably the CloudFlare cache has not purged in all locations.
