### ISSUE TITLE
Importing modules

### ISSUE THREAD

**Issue by ssimnv** [highcharts/highcharts#22346]
We use next module:

import ganttModule from 'highcharts/modules/gantt';
import NoDataToDisplayModule from 'highcharts/modules/no-data-to-display';
import patternFillModule from 'highcharts/modules/pattern-fill';

patternFillModule(Highcharts);
ganttModule(Highcharts);
NoDataToDisplayModule(Highcharts);

After update from 11.4.1 to 12.0.2 have an error for every module: TypeError: highcharts_modules_pattern_fill__WEBPACK_IMPORTED_MODULE_16___default(...) is not a function

#### Expected behaviour
Imported modules works

#### Actual behaviour
TypeError: highcharts_modules_pattern_fill__WEBPACK_IMPORTED_MODULE_16___default(...) is not a function

#### Product version
Gannt 12.0.2

**Comment by hubertkozik** [comment]
Hi @ssimnv! Since Highcharts v12 additional modules no longer require initialization. You can read more info under the "Upgrade notes" section in the changelog: https://www.highcharts.com/changelog/#highcharts-v12.0.0
