### ISSUE TITLE
V 11.4.0  Cannot find module 'highcharts' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cyhnkckali** [highcharts/highcharts#20914]
When I upgraded the version from 11.3.0 to 11.4.0, I received a warning that there is no type declaration

<img width="380" alt="image" src="https://github.com/highcharts/highcharts/assets/93313260/8ab2c136-e2db-40fc-ac1c-dcfa9ed7e5c9">

**Comment by karolkolodziej** [comment]
Hi @cyhnkckali! 

Could you please share more details with me about your issue? 
I've tried to recreate that but everything works. 

Could you please create an online demo so I can work on it?
