### ISSUE TITLE
Changelog update for v12

### ISSUE THREAD

**Issue by maruthumj** [highcharts/highcharts#22468]
#### Expected behaviour

previously it was working well when importing "import * as Highcharts from 'highcharts/highstock';" but after upgrading to version 12.0.2, It is only working when importing like this "import * as Highcharts from 'highcharts';".

similarly when I was using v11, the box chart was rendering properly when using the import "import 'highcharts/highcharts-more';" but after upgrading to version #12.0.2, it is only working when importing like this "import 'highcharts/highcharts-more.src';".

It would be appreciated if these breaking changes are included in the upgradation log. because it took lot of time to figuring out these issues on my own.  

#### Actual behaviour
Currently in the version 12 upgrade note, it is mentioned ,"When importing Highcharts as a node module, additional modules no longer require initialization". But it is breaking for some other imports as well.

**Comment by davidkarlsson** [comment]
Yeah, using highcharts-more doesn't seem to work in the version of Highcharts (12.1.2). I'm trying to use it like this which was working fine in the last version we were using:

```
import * as Highcharts from 'highcharts';
import highchartsMore from 'highcharts/highcharts-more';

highchartsMore(Highcharts);
```
In 12.1.2 this gives the following error: `Uncaught TypeError: import_highcharts_more.default is not a function`

Since I'm using ts I can't import 'highcharts/highcharts-more.src' like  @maruthumj is suggesting since that import doesn't have any types and I'm guessing that's not how you're suppose to use it now anyway? Also, if you omit the `highchartsMore(Highcharts)` call you will get an error when you try to use charts that require highcharts-more: 
```

Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=arearange
 - missingModuleFor: arearange
```
So you still have to import the module for it somehow but there just doesn't seem to be a way to do it with the latest version of Highcharts?

**Comment by hubertkozik** [comment]
Hello guys!

@maruthumj  There is an `Upgrade note` under the Highcharts v12 section in the changelog: https://www.highcharts.com/changelog/#highcharts-v12.0.0 You can check, that there is an example of how to import Highcharts now.

@davidkarlsson You shouldn't and can't initialize the modules since Highcharts v12. The types are working correctly when importing Highcharts v12.1.2: https://stackblitz.com/edit/highcharts-angular-line-nugxucvk?file=src%2Fapp%2Fapp.component.ts

**Comment by maruthumj** [comment]
> Hello guys!
> 
> @maruthumj There is an `Upgrade note` under the Highcharts v12 section in the changelog: https://www.highcharts.com/changelog/#highcharts-v12.0.0 You can check, that there is an example of how to import Highcharts now.
> 
> @davidkarlsson You shouldn't and can't initialize the modules since Highcharts v12. The types are working correctly when importing Highcharts v12.1.2: https://stackblitz.com/edit/highcharts-angular-line-nugxucvk?file=src%2Fapp%2Fapp.component.ts

I totally get the point about the import change. my point is when I use `import 'highcharts/highcharts-more';` it is not working and throwing console errors. It is only working when using `import 'highcharts/highcharts-more.src';`. please make sure whether this change is intentional from your end or not.

**Comment by hubertkozik** [comment]
@maruthumj Can you reproduce the issue with throwing console errors while using `import 'highcharts/highcharts-more';`? In my demo, from the previous post you can see, that import is done in that way and there are no errors.

**Comment by MartinDawson** [comment]
@hubertkozik Hi, I've just wasted hours on this. When you make a breaking change, in the future can you PLEASE have a simple diff on your page on the examples on how to upgrade easily, i.e like nextjs and other major frameworks do.

Going through changelogs is not good UX.

Thanks
