### ISSUE TITLE
Console errors "<text> attribute x: Expected length, "NaN"" when plotBands.label.text is set, and toggling visibility of series.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7175]
#### Expected behaviour

Clean console, and label.text should be hidden after click on series in legend.

#### Actual behaviour

1. There are lot of errors in console: **<text> attribute x: Expected length, "NaN"**
2. Label of plotBand not disappear with series, only move to the upper left corner of chart.

_Everything works correctly upper to version 5.0.9._

#### Live demo with steps to reproduce

[JSFiddle](http://jsfiddle.net/daniel_s/L20q7aka/)

1. Open console in Developer Tools.
2. Click on "Series 1" in legend.

#### Affected browser(s)

All browsers

**Comment by pawelfus** [comment]
Hi @Denyllon 

Thanks for reporting this issue!

*Internal note:*
It's a regression after 2bf1b0c

**Comment by atshaas** [comment]
Could this still be an issue for yAxis?
I can see similar recursive error message when using chart.yAxis[0].removePlotLine('plotLine');
`
highcharts.min.js:61 Error: <rect> attribute y: Expected length, "NaNNaN".
highcharts.min.js:61 Error: <rect> attribute height: Expected length, "NaNNaN".
`

**Comment by pawelfus** [comment]
Hi @atshaas 

Thanks! If you could update demo ( http://jsfiddle.net/L20q7aka/1/ - works fine) that would be great! We will look into this.

**Comment by atshaas** [comment]
Our backend bug. We accidentally changed the decimal separator for the threshold value to a comma instead of a full stop. Thus, the threshold and threshold dependent series threw an error on rendering using HighCharts.chart('container', options).

**Comment by PrathikGBS** [comment]
My version of high charts in 4.2.4, was this issue resolved in this version ?


Regards
Prathik

**Comment by PrathikGBS** [comment]
http://jsfiddle.net/L20q7aka/18/
was able to reproduce this in the above fiddle, chk the console error.

**Comment by pawelfus** [comment]
@PrathikGBS 

This is caused by [`yAxis.title.align`](https://api.highcharts.com/highcharts/yAxis.title.align) - available options are `'low'`, `'high'` and `'middle'`, not `'left'`: http://jsfiddle.net/BlackLabel/L20q7aka/59/

**Comment by PrathikGBS** [comment]
tht worked, thanks.

**Comment by nadim** [comment]
I'm getting the same error here, but only when I try applying a fullscreen class to the chart:
http://jsfiddle.net/Lxn82jdr/

Any reason why this would happen? The `config` looks OK to me. Maybe I'm missing something?

Also, not sure why the number 11 is showing on the Y axis. This is something I've been looking into for a while in a number of charts.

Would really appreciate any help, and happy to open another issue report if that's more appropriate.


+Nadim

**Comment by TorsteinHonsi** [comment]
Hi Nadim,

I can't see this error in your demo - what do you mean by applying a fullscreen class? I can't see a reference to that in the code either.

Regarding the number eleven, it is because the Y axis adds another category to make room for the bubbles, and since there is no category 11, it just prints the number. An empty string will fix that: http://jsfiddle.net/highcharts/Lxn82jdr/2/.
