### PR TITLE
bugfix/24561-wrong-type-for-lang-downloadMIDI

### LINKED ISSUE #24561: TypeScript declaration for lang.downloadMidi no longer accepts string
#### Expected behaviour
`lang.downloadMidi` should accept a string value, as it did in Highcharts 12.5.0 and as other `lang` properties still do.

For example, this should compile:

```ts
Highcharts.setOptions({
  lang: {
    downloadMidi: 'Download MIDI',
    downloadJPEG: 'Download JPEG'
  }
});
```

#### Actual behaviour
In Highcharts 12.6.0, `lang.downloadMidi` appears to have changed from accepting a string to requiring an object.

This causes a TypeScript compilation error when using a string value:
```ts
lang: {
  downloadMidi: 'Download MIDI'
}
```

#### Live demo with steps to reproduce
[12.6.0 stackblitz](https://stackblitz.com/edit/stackblitz-starters-mfrykag7?file=src%2Fmain.ts)

It can't compile in 12.6.0 as string is not allowed

#### Product version
Highcharts Core 12.6.0

Regression from v12.5.0

Workaround:
```ts
Highcharts.setOptions({
    lang: {
        // Bypassing the Highcharts .d.ts bug
        downloadMIDI: "Download MIDI" as any,
        playAsSound: "Play as sound" as any
    }
});
```

### PR DESCRIPTION
**Pull request by AndrzejBuleczka**
Fixed #24561, missing string types for sonifiaction lang options.

### CODE REVIEW

**Review by jedrzejruta — APPROVED** [review]

**Review by wchmiel — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!
