### ISSUE TITLE
Type Error on combination of export and chart.update()

### ISSUE THREAD

**Issue by rstrietzel** [highcharts/highcharts#6007]
#### Expected behaviour
The chart can be updated and exported multiple times.

#### Actual behaviour
After an export followed by an update to deactivate the legend on exports clicking anywhere leads to a Type Error: k.setState is not a function.

It's working fine with Highcharts 4.2.2, therefore probably a regression.

#### Live demo with steps to reproduce

https://jsfiddle.net/jc74psrt/1/

1. export as png
2. push the button
3. clicking anywhere leads to "TypeError: k.setState is not a function"

#### Affected browser(s)
Firefox, Chrome

**Comment by TorsteinHonsi** [comment]
_Internal note_:
Chart.update didn't exist in v4.2.2.

**Comment by TorsteinHonsi** [comment]
Observation: We may bypass the error message by checking for `button.setState`, but the issue then is that the export menu doesn't open the second time, after updating the legend.

**Comment by pawelfus** [comment]
*Internal note:*
I think the problem is with the event closures: 

We recreate the exporting button with all events, except the event with `hide()` for the context menu - we still use old button reference, because `menu = chart[cacheName]` exists (no destroying in `destroyExport()`, simple test: `chart['cache-highcharts-contextmenu'] = null;` - will show the new context menu, still with the error. Errors number will increase, because we everytime add a new event).

In `destroyExport()` we can try to remove event `removeMouseUp` (`"destroy"` chart is not called when updating the chart, right?) instead of `addEvent(chart, 'destroy', removeMouseUp);`. How does it sound?

**Comment by TorsteinHonsi** [comment]
Sounds like music to my ears 👍

**Comment by yoderexploder** [comment]
Hello, any update on this problem?
