### ISSUE TITLE
Dragging / x-panning doesn't work in Highstock [5.0.7] (this.ordinal2lin is not a function)

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6276]
#### Expected behaviour
Dragging / panning in x axis should work

#### Actual behaviour
Dragging / panning in x axis does not work

It throws an error:
```highstock.js:390 Uncaught TypeError: this.ordinal2lin is not a function```

#### Live demo with steps to reproduce
5.0.7 | http://jsfiddle.net/g0w23k11/ (Does not work)
5.0.6 | http://jsfiddle.net/g0w23k11/1/ (Works)

Occurs after fixing issue below:
https://github.com/highcharts/highcharts/issues/5979

**Comment by sebastianbochan** [comment]
Demo: 
- http://jsfiddle.net/7j76un0p/

Panning seems to still does not work.

iOS: 10.1.1
Android: 6.0.1

**Comment by TorsteinHonsi** [comment]
It's expected behaviour, see the comment on `tooltip.followTouchMove` in the docs: http://api.highcharts.com/highstock/chart.panning

**Comment by phamcharles** [comment]
@TorsteinHonsi can you shed some light on why highstocks is throwing errors in the console for trackpad (one finger click and hold and the other drag back and forth)?

**Comment by TorsteinHonsi** [comment]
Does it still do that in http://jsfiddle.net/7j76un0p/ ?

**Comment by phamcharles** [comment]
It does not happen when I used your link.

**Comment by TorsteinHonsi** [comment]
Great! Then it's fixed in the master, so next maintenance release will be good.
