### ISSUE TITLE
8.0.1 bug: this.init is not a function

### ISSUE THREAD

**Issue by jaewun** [highcharts/highcharts#13053]
#### Expected behaviour

Using the latest release on CDN, would expect page to load

#### Actual behaviour

Javascript error inside highcharts source, was working fine before 8.0.1 release 10 hours ago.

#### Live demo with steps to reproduce
https://jsfiddle.net/mfqxjo95/5/

I've include what I think caused the error, let me know if that's not enough. The implementation itself was done by a team member, but things work on 8.0.0 and not on 8.0.1

#### Product version
8.0.1

#### Affected browser(s)
Latest Chrome

**Comment by sgornick** [comment]
I'm getting this as well.

Appears to be triggered from the call to Highcharts.Color() (in your jsfiddle, line 20 where it sets the color for the second stop of the gradiant).

This impacts http://export.highcharts.com as well so hopefully this regression gets an update quick.

**Comment by oddlodd** [comment]
highcharts.src.js:2839 Uncaught (in promise) TypeError: this.init is not a function
    at Object.e [as Color] (highcharts.src.js:2839)

{
                        // RGB color
                        regex: /rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,
                        parse: function (result) {
                            return [pInt(result[1]), pInt(result[2]), pInt(result[3]), 1];
                        }
                    }];
                this.rgba = [];
                this.init(input);
            }

**Comment by factsonlineau** [comment]
Same here.
An intermediate solution in case you are in production: We downloaded 8.0.0 and referred to our local repository.

**Comment by emanuelelaface** [comment]
Same here. I downgraded to 8.0.0.

**Comment by sebastianbochan** [comment]
Hi everyone,
Thank you for reporting. We will fix it as soon as possible.

_Internal note_
It looks like a problem with `Colors` and `Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')` method.

**Comment by spenya** [comment]
Same here I just linked the 8.0.0 version from code.highcharts.

**Comment by TorsteinHonsi** [comment]
Since v8.0.1, `Highcharts.Color` must be instanciated with the `new` keyword. The changelog is not yet online, but we will add this as an upgrade note.

### Old
```js
                stops: [
                    [0, Highcharts.getOptions().colors[0]],
                    [1, new Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                ]

**Comment by spenya** [comment]
I don't understand you publish the new version without the updated changelog, especially when there are so many people using the laststable. I was mad since I found the error and figured how to fix it!!

**Comment by emanuelelaface** [comment]
May I suggest to use a major release to break the compatibility? I expect that in minor releases only fixes are pushed, and the old features and syntax should be deprecated but maintained for backward compatibility for some release before discontinue them. Anyway thanks for the insight, I will fix my script with the new keyword.

**Comment by emanuelelaface** [comment]
I just tried to add "new" but now it triggers a different error:

```
highcharts.src.js:8983 Uncaught TypeError: Cannot read property 'toString' of undefined
    at g.getTimezoneOffset (highcharts.src.js:8983)
    at g.getTimeTicks (highcharts.src.js:9234)
    at g.e.getTimeTicks (highcharts.src.js:18723)
    at g.setTickPositions (highcharts.src.js:17277)
    at g.setTickInterval (highcharts.src.js:17214)
    at g.setScale (highcharts.src.js:17515)
    at highcharts.src.js:25724
    at Array.forEach (<anonymous>)
    at e.Chart.render (highcharts.src.js:25723)
    at e.Chart.firstRender (highcharts.src.js:25969)
```

**Comment by ivanprez** [comment]
Still getting same error: this.init is not a function

**Comment by pawelfus** [comment]
@emanuelelaface , @ivanprez  - could you create demos with your issues? We will l check this.

**Comment by ivanprez** [comment]
Hi, you can view an example of our implementation at url: [https://jsfiddle.net/Stefanone_91/egvLktxs/9/](https://jsfiddle.net/Stefanone_91/egvLktxs/9/)

I have linked your cdn source: https://code.highcharts.com/highcharts.js
and until version 8.0.0 was working correctly, version 8.0.1 broken our code.
I think there is a problem with color settings, on our side we have: 

       fillColor: {
          linearGradient: {
            x1: 0,
            y1: 0,
            x2: 0,
            y2: 1
          },
          stops: [
            [0, Highcharts.getOptions().colors[0]],
            [1, Highcharts.Color(Highcharts.getOptions().colors[9]).setOpacity(0).get('rgba')]
          ]
        },


Thanks.

**Comment by pawelfus** [comment]
@IvanGuardado - check the comment above: https://github.com/highcharts/highcharts/issues/13053#issuecomment-593845663

**Comment by spenya** [comment]
it works if you just add the "new" keyword ... 
I also added a new <div id="chart"> on the html ... 
https://jsfiddle.net/dq9oy5ug/

**Comment by TorsteinHonsi** [comment]
We hear you... Will release the fix today.
