### ISSUE TITLE
v13.0.1+: `Exporting` class missing from modules/exporting.d.ts

### ISSUE THREAD

**Issue by bjornri** [highcharts/highcharts#25384]
### Expected behaviour

`chart.exporting.exportChart()`, `chart.exporting.getFilename()` and `chart.exporting.print()` type-check, as they did in 13.0.0.

### Actual behaviour

From 13.0.1 onwards, `modules/exporting.d.ts` still declares `Chart.exporting: Exporting` but no longer contains the `class Exporting { ... }` declaration that 13.0.0 had. The only remaining declaration of `Exporting` is the partial one in `modules/export-data.d.ts` (`getCSV`, `getDataRows`, `downloadCSV`, `downloadXLS`), so TypeScript reports:

```
error TS2339: Property 'exportChart' does not exist on type 'Exporting'.
error TS2339: Property 'getFilename' does not exist on type 'Exporting'.
error TS2339: Property 'print' does not exist on type 'Exporting'.
```

The runtime module still provides the methods, and `ts/Extensions/Exporting/Exporting.ts` is unchanged between the v13.0.0 and v13.0.1 tags (`export class Exporting` with public `@class` / `@name Highcharts.Exporting` and `@function Highcharts.Exporting#exportChart` doclets), so this looks like a regression in the declaration generation for the 13.0.1 build. `test/typescript-dts/modules/exporting.ts` only exercises button theme options, which is probably why it was not caught.

### Live demo / reproduction

```sh
npm i highcharts@13.1.1
grep -c "class Exporting" node_modules/highcharts/modules/exporting.d.ts    # 0
grep -c "class Exporting" node_modules/highcharts/modules/export-data.d.ts  # 1 (partial class)

npm i highcharts@13.0.0
grep -c "class Exporting" node_modules/highcharts/modules/exporting.d.ts    # 1
```

Minimal TypeScript file:

```ts
import Highcharts from "highcharts";
import "highcharts/modules/exporting";

const chart = Highcharts.chart("container", {});
chart.exporting.exportChart({ type: "image/png" }, {}); // TS2339 on 13.0.1+
```

The `highcharts/esm/modules/exporting.d.ts` entry re-exports `../../modules/exporting`, so ESM imports are affected in the same way.

### Product version

Affected: 13.0.1, 13.0.2, 13.1.0, 13.1.1. Works in 13.0.0.

### Affected browser(s)

Not browser related (TypeScript declarations only).

**Comment by magdalena-gut** [comment]
Hi @bjornri , thank you for reporting this issue! I added this to our backlog!
