### ISSUE TITLE
Jquery easing error after upgrade to 4.2.1 from 4.1.9

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#4887]
I upgraded to 4.2.1, changed the constructor as instructed, and when Highcharts loads I get 
TypeError: jQuery.easing[this.easing] is not a function
Sometimes this error keeps occurring on each animation cycle.  

The changelog is very vogue: Breaking change: Easing functions from jQuery UI no longer work. They will fall back to the default "swing" easing. With Highcharts 4.2, the easing function must be defined on the Math object itself.

Should I define an easing function on the Math object? 
I do not use JQuery UI, and am using JQuery 2.1.4. 

Cannot repro this in fiddle (apparently it does work on plain Highchatrs demo but I don't want to spent a half day trying to repo this by elimination)

Please help.

**Comment by TorsteinHonsi** [comment]
Highcharts doesn't contain a reference to jQuery.easing, so the error message probably comes from [https://github.com/jquery/jquery/blob/7751e69b615c6eca6f783a81e292a55725af6b85/dist/jquery.js#L6185](this line) in jQuery itself:

```js
https://github.com/jquery/jquery/blob/7751e69b615c6eca6f783a81e292a55725af6b85/dist/jquery.js#L6185
```
That's about as much as I can say without more debugging info. I can't immediately see how a clean install of Highcharts would interfere with the jQuery easing - perhaps you are using plugins or older module files?

If you don't want to spend half a day setting up a jsFiddle, a screenshot of the call stack would help.

**Comment by onemenny** [comment]
Thank you, 

Funny thing, It was non related to highchart code that caused it, but definitely the highcharts upgrade poped it out.
