### ISSUE TITLE
Client side export not working on latest version of Firefox (50.1.0)

### ISSUE THREAD

**Issue by cocochepeau** [highcharts/highcharts#6146]
#### Expected behaviour

Client-side exporting (PNG and JPEG) should work properly on Firefox (latest version).

#### Actual behaviour

When I try to export a chart to a PNG or JPEG format, console log is giving me "TypeError: ERROR.captureStackTrace is not a function".

Note: it's working on Chrome.

#### Live demo with steps to reproduce

Link to the current documentation's JSFiddle:
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/highcharts/exporting/offline-download/

#### Affected browser(s)

Firefox latest version (50.1.0)

**Comment by oysteinmoseng** [comment]
It's working for me on Firefox 50.0 on Windows 10.

**Comment by larsac07** [comment]
I cannot reproduce this issue in 50.1.0 on OSX. Works fine.

**Comment by oysteinmoseng** [comment]
@cocochepeau Are you running the actual jsFiddle and reproducing this issue?

**Comment by cocochepeau** [comment]
It works on 50.0.2 (Windows). I'm using AdblockPlus, HTTPSEverywhere, PrivacyBadger and Firebug.

I'll test with the same environment for 50.1.0 asap.

**Comment by cocochepeau** [comment]
Well, it's strange. Working fine on a "fresh" environment after Firefox has been updated from 50.0.2 to 50.1.0.

But I still can't export on the first one. Here is a screenshot..
![weird](https://cloud.githubusercontent.com/assets/2019778/21187447/432e78f8-c218-11e6-8c0a-19016c8983b8.png)

**Comment by oysteinmoseng** [comment]
What if you disable all plugins?

**Comment by cocochepeau** [comment]
OK, I think I got this one.

Even if I disable PrivacyBadger (only for jsfiddle site), it seems to block something. When I deactivate it completely (from addons manager) it's working fine.

The thing is that PrivacyBadger is enabled on my "fresh" environment and it works fine though.

Well, don't know what's happening here. Sorry guys!

**Comment by oysteinmoseng** [comment]
Alright, closing here as there doesn't seem like much we can do for now. Feel free to reopen if new information surfaces.
