### ISSUE TITLE
Setting extremes on the histogram chart with no data to display generates an error in the console

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14315]
#### Expected behaviour
Being able to set the extremes without error.

#### Actual behaviour
When the extremes for the histogram axis such that there is no data there to display, errors in console occurs.
```
"highcharts.src.js:3636 Error: <rect> attribute y: Expected length, "NaN"."
"highcharts.src.js:3636 Error: <rect> attribute height: Expected length, "NaN"."
```

#### Live demo with steps to reproduce
Click the button below the chart and check the console.
https://jsfiddle.net/BlackLabel/9yv5j6bq/

#### Product version
Highcharts JS v8.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
*Internal note:*
It's a general, column-like series issue: https://jsfiddle.net/BlackLabel/dkwzt5e8/

Bisected to commit d722bdc378
