### ISSUE TITLE
Cannot import modules when using Typescript

### ISSUE THREAD

**Issue by felhag** [highcharts/highcharts#23146]
I have a project using Highcharts with Typscript and Angular 20 (but I don't think it's an Angular issue). Since Highcharts 12 I can't seem to import modules anymore.

#### Expected behaviour
```
import more from 'highcharts/highcharts-more';
more(Highcharts);
```
Should work

#### Actual behaviour
It gives the following error: 
`Uncaught TypeError: more is not a function`

Same issue seems to appear when using other modules like `heatmap` or `exporting`.

#### Live demo with steps to reproduce

1. Create new Angular project using `ng new`
2. Add latest Highcharts version (12.2.0) in `package.json`
3. Add code snippet specified under Expected behaviour 
4. Run `ng serve`
5. Open browser on `localhost:4200` and see error in console

#### Product version
Highcharts 12+. It seems to work fine using Highcharts 11.4.8

#### Affected browser(s)
Brave

**Comment by KacperMadej** [comment]
Hi @felhag 

Please see upgrade notes for v12 - https://www.highcharts.com/changelog/#highcharts-v12.0.0

Since v12, the module will not return a factory function.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/22579

**Comment by felhag** [comment]
@KacperMadej, totally missed this. Thanks for the quick response!
