### ISSUE TITLE
onContainerMouseDown error in QtWeb browser (wkhtmltopdf)

### ISSUE THREAD

**Issue by daveherman71** [highcharts/highcharts#13457]
#### Expected behaviour
The chart is expected to show.

#### Actual behaviour
The chart does not show.

When loading the HTML page the following error appears in the console.
```
TypeError: 'undefined' is not a function (evaluating 'this.onContainerMouseDown.bind(this)')
highcharts.js:264
```

#### Live demo with steps to reproduce
```
<html>
<head>
<script src="https://code.highcharts.com/highcharts.js"></script>
</head>

<body>
<div id="container"></div>
<script type="text/javascript">

	Highcharts.chart('container', {
		xAxis: {
			categories: ['Apples', 'Pears', 'Bananas', 'Oranges']
		},
		series: [{
			data: [1, 4, 3, 5],
			type: 'column'
		}]
	});

</script>
</body>
</html>
```

#### Product version
 Highcharts JS v8.1.0 (2020-05-05)

#### Affected browser(s)
QtWeb as well as wkhtmltopdf and therefore any other applications that embed the Qt webkit browser

**Comment by KacperMadej** [comment]
Hi @daveherman71 

Thank you for reporting the problem.
QtWeb is not one of the [supported browsers](https://www.highcharts.com/docs/getting-started/system-requirements#browser-compatibility).

I tried debugging, but the browser lags and hangs before I am able to check what is causing the error. If you are able to debug the problem please share some details about the problem.

With only information about the error, it looks like a browser error because other browsers are not showing this problem.

This happens only for files and online works fine e.g. https://www.highcharts.com/demo/line-basic is showing the chart correctly in the QtWeb.

**Comment by daveherman71** [comment]
Hi @KacperMadej 

I use _wkhtmltopdf_ (https://wkhtmltopdf.org/) to render HTML to PDF. The application uses the Qt WebKit rendering engine and it requires that an HTML page first be rendered to disk and then from there you can use the _wkhtmltopdf_ CLI to convert the HTML file to PDF.

I had previously been using v7.2.0 without any problems however when I updated yesterday to v8.1.0 the error occurred. The problem does not seem to exist in v8.0.4 and earlier.

The _wkhtmltopdf_ CLI parameters are as follows:
```
wkhtmltopdf.exe --enable-javascript --javascript-delay "3000" --debug-javascript
"C:\Test\highcharts_test.html" "C:\Test\highcharts_test.pdf"
```

When executing this with v8.0.4 the output is as expected and the PDF is rendered correctly:
```
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

However, when executing with v8.1.0 the output shows an error and the PDF file is blank:
```
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

Unfortunately _wkhtmltopdf_ does not show any other Javascript debugging info so you have to to open the HTML file in QtWeb using the **file://** protocol in order emulate the process so that you are able to see additional error details in the JS console:
```
TypeError: 'undefined' is not a function (evaluating 'this.onContainerMouseDown.bind(this)')
highcharts.js:264
```

I agree that it is likely a browser issue with the QtWeb WebKit rendering engine but it has worked correctly up to now and we have to stay with _wkhtmltopdf_ due to its exceptional speed and performance. I would hate to have to move my clients to a different charting tool.

I tried disabling mouse events on the series in plotoptions but that did not work so it might just need something like checking for `undefined` before binding the event.

I have attached a simple HTML file and the valid PDF that is created using highcharts.js v8.0.4 (rename the .txt file to .html before executing) however changing to highcharts v.8.1.0 results in the error.

[highcharts_test.txt](https://github.com/highcharts/highcharts/files/4592976/highcharts_test.txt)
[highcharts_test.pdf](https://github.com/highcharts/highcharts/files/4592977/highcharts_test.pdf)

**Comment by pawelfus** [comment]
This is bug in wkhtmltopdf, see: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2587 - try ot use workaround posted there.

**Comment by daveherman71** [comment]
Thanks @pawelfus - the workaround did the job.

**Comment by pragneshmpatel** [comment]
Hi @daveherman71 ,
I have similar issue with phantomjs. 
which file do we add this extra code? When I try to add on top of the highcharts.js it crashes phantomjs.

**Comment by daveherman71** [comment]
Hi @pragneshmpatel,

I haven't used phantomjs but this is how I load the extra code:

```
Function.prototype.bind = Function.prototype.bind || function (thisp) {
	var fn = this;
	return function () {
		return fn.apply(thisp, arguments);
	};
};

jQuery.ajax({ url: '//code.highcharts.com/highcharts.js', dataType: 'script', cache: true, success: function( data, textStatus, jqXHR ) {

	jQuery.ajax({ url: '//code.highcharts.com/modules/data.js', dataType: 'script', cache: true, success: function( data, textStatus, jqXHR ) {
		// All your highcharts code here
	}
}
```

**Comment by daveherman71** [comment]
This StackOverflow thread might also help [https://stackoverflow.com/questions/27659514/phantomjs-function-prototype-bind](https://stackoverflow.com/questions/27659514/phantomjs-function-prototype-bind)
