### ISSUE TITLE
setData does not work with pie charts

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#542]
Applies to In the new master branch containing stock src.
1. Open http://jsfiddle.net/7TTNM/
2. Click 'change data' to invoke setData with a new array of values

Result: Javascript error: `point.getLabelConfig is not a function`

Expected: A nice pie chart. (Works in 2.1.7, change 'master' in the url to 'v2.1.7' to test)

**Comment by chriscareycode** [comment]
This issue seems to be back somewhere after HighCharts 4.1.4 and is still present in 4.2.3.

HighCharts 4.1.4 does not have the bug.
