### ISSUE TITLE
Unable to run Highcharts in the newer versions of Node.js

### ISSUE THREAD

**Issue by kogratte** [highcharts/highcharts#21477]
#### Expected behaviour

We're working on a shared private package which provides some components based on HC. Those components where working well in a monolithic design. 

As soon as we move them into our shared packages, we're seeing a strange behaviour:

`NetworkGraph is not a function`.

We're using the latest package version, and follow installation instructions line by line.

#### Actual behaviour

`NetworkGraph is not a function`.

**Comment by karolkolodziej** [comment]
Hi @kogratte 
We had some issues with the packages' names and their location. 
Could you please install the latest `v11.4.6` and test if it works?

**Comment by kogratte** [comment]
Of course. I'll let you know.

Le mer. 10 juil. 2024 à 08:01, Karol Kołodziej ***@***.***> a
écrit :

**Comment by BenPortner** [comment]
Hi @karolkolodziej 

I'm seeing a very similar behavior. I installed Highcharts v11.4.6 via npm. Importing Highcharts somehow returns a function instead of a module/object. Minimal example below. 

```node.js
var Highcharts = require("highcharts");

typeof Highcharts // 'function'

Highcharts.chart(); // Uncaught TypeError TypeError: Highcharts.chart is not a function
```

**Comment by karolkolodziej** [comment]
@BenPortner  A few things are missing here to recreate it. I'm not sure of your environment because I was able to successfully load the Highcharts with `require` in a React demo. 

Is your case different? Could you please share a minimal demo where this issue is visible?

**Comment by BenPortner** [comment]
@karolkolodziej,
Which pieces of information are you missing? I believe my post contains everything needed to recreate the problem:
1. Install Highcharts v11.4.6 via npm
2. Create a main.js file with the content that I posted above
3. Run `node main.js` -> the given error occurs.

Please let me know what information is missing or how else to "share a minimal demo".

**Comment by karolkolodziej** [comment]
Thank you, @BenPortner, for giving me the steps.
I can recreate it but I still don't get one small detail.

Why would you use Node.js to execute `Highcharts.chart`? Where do you expect to render it without the DOM/window?

[Here you can see how it works in a browser environment with `require`.](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/amd/simple/)

**Comment by BenPortner** [comment]
Hello @karolkolodziej,

`Highcharts.chart` is just a placeholder for the minimal example. What I really want to use is helper functions like Highmaps.geojson. But these don't work either because the exports are broken.

I also had a look at your example. Unfortunately it doesn't really help me to solve my problem. What I want to do is use Highcharts in nodejs. Not call require.js in a browser...

**Comment by karolkolodziej** [comment]
Ok now I see and I understand! The Highcharts exports a function that you need to call and this should solve your issue on the server side.

```ts
const Highcharts = require('highcharts')();
```

[See the grouping on the server side example](https://github.com/highcharts/highcharts/blob/master/test/node-datagrouping.js)

**Comment by BenPortner** [comment]
Thanks, but I've tried that of course.

```node
var Highcharts = require("highcharts")();
```

yields

> Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'dispatchEvent')

**Comment by karolkolodziej** [comment]
I have this very simple `main.js` file:
```js
var Highcharts = require("highcharts")();

console.log(typeof Highcharts);
```

with:
```json
  "dependencies": {
    "highcharts": "^11.4.6"
  }
```

and I'm able to run it without any error:
```bash
 karolkolodziej: ~/testFolder/require-hc
🌵 >node main.js
object
```

**Comment by BenPortner** [comment]
That's strange. I cannot get it to run. I've used exactly the same main.js and exactly the same package.json as you described. I tried: 
- on Windows with Node v22.51
- on WSL via docker with Node v22.3.0 
- on WSL via docker with Node v20.15.1

I get the same error every time. Can you confirm that it runs with docker and node:22-slim on your machine?:

`docker run -it -v "$PWD":/usr/src/app -w /usr/src/app node:22-slim node src/main.js`

**Comment by karolkolodziej** [comment]
Previously I was on the node `v18.18.0` and the `CustomEvent` is not defined there.
But when I change it to anything newer (`v20.10.0`) I get the same error:
```
TypeError: Cannot read properties of undefined (reading 'dispatchEvent')
    at i (/Users/karolkolodziej/testFolder/require-hc/node_modules/highcharts/highcharts.js:7:433)
    at /Users/karolkolodziej/testFolder/require-hc/node_modules/highcharts/highcharts.js:7:528
    at Object.<anonymous> (/Users/karolkolodziej/testFolder/require-hc/main.js:18:41)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0
```

Now since the `CustomEvent` is exposed in the Node.js[ this check might not be sufficient. ](https://github.com/highcharts/highcharts-assembler/blob/358daaddefaf1dfdf9788b612bd937c8ce247d52/src/templates/umd-standalone.txt#L24)

**Comment by BenPortner** [comment]
So that's the root of the evil! Thanks for figuring that out 🎉 Do you have any idea how long it is going to take to fix it?

**Comment by karolkolodziej** [comment]
We will come up with a solution within a few weeks.

**Comment by MarkusBarstad** [comment]
Bugfix is done and will be part of next release some time next week, make sure you reinstall Highcharts when the time comes,  @BenPortner @kogratte

**Comment by BenPortner** [comment]
Hello @MarkusBarstad @karolkolodziej 

Unfortunately, the problems persist even with the new version 11.4.7. I importing any of the highcharts modules fails. For example, this code from https://www.highcharts.com/docs/getting-started/installation-with-amd-commonjs does not work with NodeJS 22.7.0:

```node
var Highcharts = require('highcharts');
require('highcharts/modules/exporting')(Highcharts);  // TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
```

I also tried these variations without success:
```node
var Highcharts = require('highcharts')();
require('highcharts/modules/exporting')(Highcharts);  //TypeError: e.win.dispatchEvent is not a function
```
```node
var Highcharts = require('highcharts')();
require('highcharts/modules/exporting')();  //TypeError: Cannot read properties of undefined (reading 'win')
```
```node
var Highcharts = require('highcharts')();
var foo = require('highcharts/modules/exporting');
typeof foo // function
```

I request that the issue be reopened.

**Comment by karolkolodziej** [comment]
You are right Ben this issue is still visible even when using the latest v11.4.8.
@MarkusBarstad Could you please investigate it once again?

**Comment by BenPortner** [comment]
@karolkolodziej any news?

**Comment by MarkusBarstad** [comment]
> You are right Ben this issue is still visible even when using the latest v11.4.8. @MarkusBarstad Could you please investigate it once again?

@karolkolodziej @BenPortner Apologies for the delayed response, I will look into this.

**Comment by BenPortner** [comment]
@MarkusBarstad thanks for looking into this. Can you share any news? :)

**Comment by josenoriega-procore** [comment]
Facing the same issue on `v12.1.2`

Node `v20.16.0`
TS `v5.7.3`

**Comment by BenPortner** [comment]
*push*

**Comment by MarkusBarstad** [comment]
@BenPortner Hey Ben, and apologies for not getting back to you!

Right now we are in the process of rebuilding some of the module related tooling, I would imagine that this should solve this issue, but I am not sure.

I will ask those working on it for an ETA/any ideas on this issue

**Comment by MarkusBarstad** [comment]
Hey @BenPortner and @kogratte  

After some discussion with the team, I regretfully inform you that we will not support Highcharts in node at this time.

Do note that it is possible to access a vanilla Highcharts-object in node as such:
```
import Highcharts from "./code/es-modules/masters/highcharts.src.js"
```

...But that is about the extent of what works (apart from a few functions available there). 

- Calling `Highcharts.chart()` will break the script because it expects the id of a DOM element. 
- Importing alternative/additional modules will break the script because our modules all augment vanilla Highcharts, and DOM stuff is used in this process.


Potential workaround:
- Perhaps `jsdom`/`linkedom` and the like could provide the DOM API needed. 
- One could try to alter Highcharts locally so that it initialize the properties `doc` and `win` to whatever 'dummy' document/window your solution provides.

Sorry that we could not help you guys further!
