### ISSUE TITLE
updateTransform - Trailing garbage Inifinity

### ISSUE THREAD

**Issue by ahansen1** [highcharts/highcharts#22009]
#### Expected behaviour
When clicking into a cluster and firing the drillToCluster event the graph drills to the cluster without producing errors.

#### Actual behaviour
When clicking a cluster and triggering a drillToCluster event the browser errors with the following error message under very specific conditions:

`highcharts.js:8 Error: <image> attribute transform: Trailing garbage, "…497.08333333893,-Infinity) scale…".`

Conditions:

1. The min/max of the graph are the same
2. A boosted series exists in the graph

The error is thrown because the translate transform here where h or l = Infinity or -Infinity.

```javascript
            updateTransform(t="transform") {
                let {element: e, matrix: i, rotation: s=0, rotationOriginX: r, rotationOriginY: o, scaleX: n, scaleY: a, translateX: h=0, translateY: l=0} = this
                  , d = ["translate(" + h + "," + l + ")"];
``` 

#### Live demo with steps to reproduce[
https://jsfiddle.net/8Lj4eaof/1

1. Open the developer tools (does not show in the fiddle console pane)
2. Click the cluster marker to zoom
3. Observe the noted error

#### Product version
Tested against latest (11.4.8) had highcharts, boost, and marker-clusters enabled.

#### Affected browser(s)
Assume all

**Comment by hubertkozik** [comment]
Hi @ahansen1! Thank you for reporting the bug. It's a regression, worked correctly in Highcharts v11.4.1.

I've prepared a workaround for you until it is fixed natively: https://jsfiddle.net/BlackLabel/2pmczLye/ If you want to use it in your project you can copy-paste the IIFE plugin.

_Internal note_
Bisected to dae8f787ea678ac6f7d92a8411e1f8d8d3dc7644.
