### ISSUE TITLE
Offline export working weirdly with many points

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#6110]
#### The setup
I'm plotting three charts in the same page. The first one is quite dense on data points and may (depending on the time interval selected) contain a fairly big amount of them; in a common case we may be talking about 20 000 of them. The following two contain relatively very few data points.

My goal is to export them all as a single file.

#### Expected behaviour
Whatever is in the screen, should be exported.

#### Actual behaviour
Up to a few thousands data points, everything works as expected. However, when the number of data point increases, the behaviour is quite odd and depends on the type:
- If it is PDF, a 1px by 1px blank PDF is downloaded.
- Otherwise (PNG, JPEG, SVG), a file is produced where the second chart in the screen becomes the first on the file, and the third chart on the screen becomes the second *and* the third on the file (so it is effectively duplicated, and the first image on the screen – the heavy one – disappears completely).

#### Live demo with steps to reproduce
I was trying to reproduce this before reporting #6108. However, I wasn't able to. Here is my attempt to do so, in case it is of any help http://jsfiddle.net/inad9300/869ftho6/

I'm sorry I cannot provide more information. It is a really weird and annoying error. What I could say in addition is that the `svgResult` callback on the example is effectively called twice with the SVG corresponding to the second chart.

#### Affected browser(s)
At least Chrome and Firefox, with the exact same behaviour in both.

**Comment by oysteinmoseng** [comment]
Closing this as duplicate of #6110, follow up there.

**Comment by inad9300** [comment]
Sorry, but why did you marked the issue as duplicated? Even though their titles share some words, they are two different problems.

#6110 implies that the file that you download is incorrect, showing a blank document if you export it as PDF, and showing the wrong charts if you export it as a graphic. This, I was not able to reproduce; however, while trying to do so I found out...

#6108, which is a different case, where the download works as it should except for the combination Chrome + PDF, in which case there is a "Network error" (I will add a screenshot with the error to the other issue).

**Comment by oysteinmoseng** [comment]
Sorry, I misunderstood you. This could still be related to #6108 as we found a limitation in Chrome on length of data URIs that would cause all kinds of chaos. Without a way to reproduce this issue it would be difficult to debug this specific problem, though. Hopefully a fix for #6108 will do the trick.

**Comment by oysteinmoseng** [comment]
We have now pushed a fix for #6108, would you check if this issue still stands? You can load the latest code from our `hc5-fixes` branch on github by using `http://github.highcharts.com/hc5-fixes/modules/offline-exporting.js`

**Comment by inad9300** [comment]
It's not easy for me to test the code like this, due to the development setup. Please let me now when this feature gets released and I'll have no problems testing it then.

I have also an idea to tell you. Since the offline downloads are giving problems so often, and usually the source of the problem is a big number of points. why not limit it for download? The same ideas behind the [boost module](http://www.highcharts.com/news/175-highcharts-performance-boost) could be used here as well, meaning avoid drawing beyond what the user can perceive, depending on the size specified for the download.

**Comment by inad9300** [comment]
Have you guys given any thought to the possibility of limiting the number of points for the downloads?

**Comment by oysteinmoseng** [comment]
@inad9300 It sounds like a good idea, but the issue with it is that you would lose zooming detail. For raster images (PNG/JPEG) optimizing should not make a difference, as the chart is converted to pixels anyway. For SVG and PDF - which are vector based - you wouldn't want to remove detail from the chart in case the user wants to zoom in on the exported chart sometime, or blow it up to a larger size. It could be optional functionality, though. You could submit a ticket in our [UserVoice](https://highcharts.uservoice.com/forums/55896-general) forum about this, if you'd like.

I do believe we are handling charts with large datasets well now, though, so hopefully this won't be an issue - at least in modern browsers.

**Comment by inad9300** [comment]
I see, thanks for the follow up.

I don't have any particular interest on reducing the resolution _per se_, the only thing that concerns me is the working status of the (offline) downloads. By this I mean that I don't see a need for submitting a ticket on your forum if the downloads are already handled properly. If I experiment any related problem in the future, I'll open an issue here.

**Comment by inad9300** [comment]
I was re-testing my code again after coming back to this issue. The first times I tried I experimented a _very_ weird error, which repeated consistently independently of the amount of data. (I can control it by reducing or modifying the values for two inputs on a form which represent the start and end of a period of time, which are sent to the underlying database query.) Here it is a Paint-based representation of my case (left: charts on the webpage; right: printed charts, any format but PDF -- which produces a 1px by 1px blank image, as happens in other cases):

![crude_diagram_2](https://cloud.githubusercontent.com/assets/3440331/22016436/9559038e-dca6-11e6-85cd-b160900723ef.png)

Surprisingly, I started looking into the code trying to understand the problem. I changed I couple of things, and after refreshing the page a few times the error was gone. Since the only things I changed were apparently irrelevant, I changed them back, only to find out that the error didn't come back. So, it seems it magically fixed itself, but I'm afraid it will come back at some point if the same (unknown for me) conditions are met.

Now, the following attempts worked as before, showing the problems described above when the issue was opened. Unfortunately, this error is consistently happening. I would like to add a similar diagram for this case, for you to have a better understanding of the problem (which I suspect has to do with asynchronous operations):

![crude_diagram](https://cloud.githubusercontent.com/assets/3440331/22016435/95587248-dca6-11e6-8afa-0195158a2b7b.png)

**Comment by oysteinmoseng** [comment]
Version `5.0.7` is out now, so I would recommend testing with that one, which has some fixes related to offline download.

That being said, this does sound more related to async issues with getting the SVGs of charts. It's possible that it could be fixed by waiting for the finished SVG result for each chart before asking for the next one. In the linked [jsFiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/exporting/multiple-charts-offline) we would be talking about changing the `for` loop in `Highcharts.getSVG`. I will look more into this for the FAQ fiddle, but you could also try making similar changes to your code.

**Comment by inad9300** [comment]
Thanks for keeping me up.

I confirm that updating to 5.0.7 has not effect at all on the open issue, however... I tried your suggestion in a hacky way (adding a timeout for each loop), and it does indeed solve the problem, even with a delay as little as 10 milliseconds.

I was somehow hoping for Highcharts to handle this under the hood. Now I realize this hope was nonsense: each call to `getSVGForLocalExport` returns its own callback and is independent from all the others. It would be good to update the example to at least warn about this fact. I'll probably solve this using promises, but without them I cannot see how to do it -- sorry I cannot be of more help in this regard.

**Comment by inad9300** [comment]
For completeness, I have tested the suggested modification and it works for all data formats except for PDF, where the error is different now (it refers to a file named `svg2pdf.js`): `Uncaught TypeError: o.addImage is not a function`.

The error doesn't show up with very small amount of data, only when it starts getting _big_ (around 0.5MB).

**Comment by oysteinmoseng** [comment]
@inad9300 Highcharts should ideally handle this, but currently there is a certain chance of race conditions for technical reasons. Recursion is a good way to handle this, and I will update our FAQ demo to reflect this.

I successfully exported a 3.5MB+ PDF on Chrome using this approach. Are you able to reproduce your issue in a jsFiddle?

**Comment by PavaniKa** [comment]
We have the same issue with v5.0.7. The below code works with v5.0.6, but not with 5.0.7. We had really hard time in figuring out why this was working in our local dev environments, but not on the deployed apps on servers.

We load highcharts with bower, so to fix this issue we had to explicitly mention the version number to "5.0.6" from "^5.0.2"

```
chartConfig.exporting = {
            fallbackToExportServer: false,
            sourceWidth: 1200,
            scale: 2,
            filename: 'Report-Name-' + moment().format('MMDDYYYY'),
            chartOptions: {
                title: {
                    useHTML: true,
                    text: 'Linear Ratings Report',
                },
            }
        };
```

**Comment by KacperMadej** [comment]
Closing due to inactivity.
