### ISSUE TITLE
Highcharts 8.1.1+ TS8010 error

### ISSUE THREAD

**Issue by ahlgreno** [highcharts/highcharts#13775]
I recently upgraded to Highcharts 8.1.1 to fix a security vulnerability. After this, I was unable to compile my angular application. Version 8.1.0 and below compile with no issues, but anything 8.1.1 or greater will not compile.

#### Expected behaviour
Application compiles

#### Actual behaviour
```
ERROR in node_modules/highcharts/highcharts.d.ts(781,51): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/highcharts/highcharts.d.ts(781,60): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/highcharts/highcharts.d.ts(781,69): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/highcharts/highcharts.d.ts(781,78): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/highcharts/highcharts.d.ts(781,87): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/highcharts/highcharts.d.ts(781,96): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/highcharts/highcharts.d.ts(781,105): error TS8020: JSDoc types can only be used inside documentation comments.
```

#### Product version
Highcharts: `8.1.1+`
`8.1.0` and below will compile
Typescript: `^2.9.2`

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @ahlgreno 

Thank you for reporting the issue. It seems you are using old version of TypeScript (v2). Could you check v3 and let us know the results? Thanks!

FYI @bre1470

**Comment by atanu21000** [comment]
Can you please update TS version dependency into **_Dependencies_** section of npmjs? It will be helpful for others.

**Comment by bre1470** [comment]
@atanu21000 Thanks for you feedback! Bugfix https://github.com/highcharts/highcharts/pull/13786 will be released in a few weeks and will make it unnecessary to change the TypeScript version. Doing so would otherwise break the compatibility with older Angular projects relying on TypeScript v2.9+.
