### ISSUE TITLE
Zoom selection broken in 7.1.2

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#11369]
#### Expected behaviour

Zoom selection works well.

#### Actual behaviour

After selecting an area and releasing the cursor, the selected area remains highlighted and being resized as the mouse moves. With every click the zoom works, though.

#### Live demo with steps to reproduce

Sorry, no time... Here is the error message I get in the console both in the beginning and with every click:

```
TypeError: p.show is not a function
    at q.applyZones (highcharts.js:349)
    at q.render (highcharts.js:352)
    at q.d (boost.js:63)
    at q.a.<computed> [as render] (highcharts.js:22)
    at eval (highcharts.js:292)
    at Array.forEach (<anonymous>)
    at a.Chart.renderSeries (highcharts.js:292)
    at a.Chart.render (highcharts.js:294)
    at a.Chart.firstRender (highcharts.js:297)
    at a.Chart.eval (highcharts.js:271)
```

#### Product version

7.1.2 (7.1.1 works as expected).

#### Affected browser(s)

Firefox, Brave.

**Comment by pawelfus** [comment]
Hi @inad9300 

Thanks for reporting the issue, but without live demo we can not acknowledge this as a bug. Official demo work without issues, so please recreate this in jsFiddle. Thank you.

Working demo: https://www.highcharts.com/demo/line-time-series

**Comment by inad9300** [comment]
There you go! 🙂 This is the smallest example I was able to come up with. It seems to be related to the [multicolor series plugin](https://www.highcharts.com/products/plugin-registry/single/33/Multicolor%20series). Something that you introduced in 7.1.2 seems to have broken compatibility with it.

[Demo in JSFiddle](https://jsfiddle.net/tdqyfp32/8/).

**Comment by pawelfus** [comment]
Thanks for the example! Bisected to commit ca86936417 - could you create issue on the plugin's repo?

**Workaround:**
Demo:
https://jsfiddle.net/BlackLabel/ca59gymr/1/

Snippet: 
```js
(function(H) {
  H.wrap(H.Series.prototype, 'applyZones', function(proceed) {
    var graph = this.graph;

    if (graph && H.isArray(graph)) {
      graph.show = function() {
        graph.forEach(function(subGraph) {
          subGraph.show();
        });
      };
      graph.hide = function() {
        graph.forEach(function(subGraph) {
          subGraph.hide();
        });
      };
    }

    return proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  });
})(Highcharts);
```
