### ISSUE TITLE
DataPool cannot load connectors with prototype-named IDs

### ISSUE THREAD

**Issue by OskarEichler** [highcharts/highcharts#25135]
#### Expected behaviour

Connector IDs are strings and should work independently of properties inherited by ordinary JavaScript objects. IDs such as `toString` and `__proto__` should load like any other ID.

#### Actual behaviour

The connector and waiting registries are initialized as `{}` and read without own-property checks. For `toString`, `getConnector()` reads inherited functions as both an existing connector and waiting list, skips loading, then attempts `waitingList.push(...)` on that function and throws. `__proto__` is likewise unsafe as a registry key.

#### Live demo with steps to reproduce

```ts
const pool = new DataPool({ connectors: [{
    id: "toString", type: "CSV", csv: "x\n1"
}] });
await pool.getConnector("toString");
// TypeError: waitingList.push is not a function
```

#### Product version

Current `master` (`48b5b3e99a0fa9aae9a357165a5a916f504afeca`).

#### Affected browser(s)

All environments; this is string-keyed registry storage.

**Comment by sebastianbochan** [comment]
Hi,
Thank you for reporting.

This seems to be a theoretical edge case rather than a real-world issue. Could you provide a concrete production use case where it could happen?

"__proto__" is not one of the officially supported connector type / id and would need to be explicitly supplied by the developer. Without a realistic scenario where this can happen in normal usage, I don’t think there’s a strong case for making this change.

I closed the PR, please reopen when we can identify the production scenario.
