### ISSUE TITLE
Property 'rect' does not exist on type 'SVGRenderer'.

### ISSUE THREAD

**Issue by Serg-Mois** [highcharts/highcharts#13678]
After update to v8.1.1 get a lot of errors on chart.renderer field

Per documentation it's not deprecated:
https://api.highcharts.com/class-reference/Highcharts.Chart#renderer
https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#rect

Property 'g' does not exist 
on type 'SVGRenderer'.
Property 'box' does not exist 
on type 'SVGRenderer'.
and other.

**Comment by oliverlangan** [comment]
I noticed that this file's name was changed between 8.1.0 and 8.1.1—only in capitalization. SVGRenderer.js -> SvgRenderer.js.

If you're on a case sensitive OS, check your import path.

**Comment by Serg-Mois** [comment]
> I noticed that this file's name was changed between 8.1.0 and 8.1.1—only in capitalization. SVGRenderer.js -> SvgRenderer.js.
> 
> If you're on a case sensitive OS, check your import path.

It's angular 9 project. And this fields are missed in:
...\node_modules\highcharts\highcharts.d.ts

**Comment by sebastianbochan** [comment]
FYI @bre1470
